apiVersion: operators.coreos.com/v1alpha1
kind: ClusterServiceVersion
metadata:
  annotations:
    alm-examples: |-
      [
        {
          "apiVersion": "charts.kcp.io/v1alpha1",
          "kind": "Kcp",
          "metadata": {
            "name": "kcp-sample"
          },
          "spec": {
            "audit": {
              "enabled": false,
              "log": {
                "dir": "/var/audit",
                "maxAge": "10",
                "maxBackup": "1",
                "maxSize": "250"
              },
              "policy": {
                "config": "# Log all requests at the Metadata level.\napiVersion: audit.k8s.io/v1\nkind: Policy\nrules:\n- level: Metadata\n",
                "dir": "/etc/kcp/audit",
                "fileName": "audit-policy.yml"
              },
              "volumeClassName": "gp2-csi",
              "volumeSize": "1Gi"
            },
            "certificates": {
              "privateKeys": {
                "algorithm": "RSA",
                "size": 2048
              },
              "subject": {}
            },
            "etcd": {
              "cpuRequest": "500m",
              "enabled": true,
              "image": "quay.io/coreos/etcd",
              "memoryLimit": "20Gi",
              "memoryRequest": "2Gi",
              "profiling": {
                "enabled": false
              },
              "tag": "v3.5.4",
              "volumeSize": "8Gi"
            },
            "externalHostname": "kcp",
            "githubUserEditAccess": [
              "test"
            ],
            "kcp": {
              "cpuRequest": "100m",
              "etcd": {
                "clientCertificate": {
                  "commonName": "root",
                  "issuer": "etcd-client-issuer"
                },
                "serverAddress": "https://etcd:2379"
              },
              "extraFlags": [],
              "image": "ghcr.io/kcp-dev/kcp",
              "logicalClusterAdminFlag": true,
              "memoryLimit": "20Gi",
              "memoryRequest": "5Gi",
              "profiling": {
                "enabled": false,
                "port": 6060
              },
              "tag": "latest",
              "v": "3",
              "volumeClassName": "gp2-csi",
              "volumeSize": "1Gi"
            },
            "kcpFrontProxy": {
              "certificate": {
                "issuerSpec": {
                  "acme": {
                    "privateKeySecretRef": {
                      "name": "kcp-front-proxy-issuer-account-key"
                    },
                    "server": "https://acme-v02.api.letsencrypt.org/directory",
                    "solvers": [
                      {
                        "http01": {
                          "ingress": {
                            "serviceType": "ClusterIP"
                          }
                        }
                      }
                    ]
                  }
                }
              },
              "gateway": {
                "className": "",
                "enabled": false
              },
              "image": "ghcr.io/kcp-dev/kcp",
              "ingress": {
                "annotations": {},
                "enabled": false,
                "secret": ""
              },
              "openshiftRoute": {
                "enabled": true
              },
              "profiling": {
                "enabled": false,
                "port": 6060
              },
              "shardsKubeConfigFlag": true,
              "tag": "latest",
              "v": "4"
            },
            "oidc": {}
          }
        }
      ]
    capabilities: Basic Install
    createdAt: "2023-02-07T11:28:38Z"
    operators.operatorframework.io/builder: operator-sdk-v1.27.0
    operators.operatorframework.io/project_layout: helm.sdk.operatorframework.io/v1
  name: kcp-operator.v0.0.1
  namespace: placeholder
spec:
  apiservicedefinitions: {}
  customresourcedefinitions:
    owned:
    - kind: Kcp
      name: kcps.charts.kcp.io
      version: v1alpha1
  description: Kubernetes-like control plane
  displayName: kcp
  icon:
  - base64data: ""
    mediatype: ""
  install:
    spec:
      clusterPermissions:
      - rules:
        - apiGroups:
          - ""
          resources:
          - namespaces
          verbs:
          - get
        - apiGroups:
          - ""
          resources:
          - secrets
          verbs:
          - '*'
        - apiGroups:
          - ""
          resources:
          - events
          verbs:
          - create
        - apiGroups:
          - charts.kcp.io
          resources:
          - kcps
          - kcps/status
          - kcps/finalizers
          verbs:
          - create
          - delete
          - get
          - list
          - patch
          - update
          - watch
        - apiGroups:
          - ""
          resources:
          - pods
          - services
          - services/finalizers
          - endpoints
          - persistentvolumeclaims
          - events
          - configmaps
          - secrets
          verbs:
          - create
          - delete
          - get
          - list
          - patch
          - update
          - watch
        - apiGroups:
          - apps
          resources:
          - deployments
          - daemonsets
          - replicasets
          - statefulsets
          verbs:
          - create
          - delete
          - get
          - list
          - patch
          - update
          - watch
        - apiGroups:
          - authentication.k8s.io
          resources:
          - tokenreviews
          verbs:
          - create
        - apiGroups:
          - authorization.k8s.io
          resources:
          - subjectaccessreviews
          verbs:
          - create
        serviceAccountName: kcp-operator-controller-manager
      deployments:
      - label:
          app.kubernetes.io/component: manager
          app.kubernetes.io/created-by: kcp-operator
          app.kubernetes.io/instance: controller-manager
          app.kubernetes.io/managed-by: kustomize
          app.kubernetes.io/name: deployment
          app.kubernetes.io/part-of: kcp-operator
          control-plane: controller-manager
        name: kcp-operator-controller-manager
        spec:
          replicas: 1
          selector:
            matchLabels:
              control-plane: controller-manager
          strategy: {}
          template:
            metadata:
              annotations:
                kubectl.kubernetes.io/default-container: manager
              labels:
                control-plane: controller-manager
            spec:
              affinity:
                nodeAffinity:
                  requiredDuringSchedulingIgnoredDuringExecution:
                    nodeSelectorTerms:
                    - matchExpressions:
                      - key: kubernetes.io/arch
                        operator: In
                        values:
                        - amd64
                        - arm64
                        - ppc64le
                        - s390x
                      - key: kubernetes.io/os
                        operator: In
                        values:
                        - linux
              containers:
              - args:
                - --secure-listen-address=0.0.0.0:8443
                - --upstream=http://127.0.0.1:8080/
                - --logtostderr=true
                - --v=0
                image: gcr.io/kubebuilder/kube-rbac-proxy:v0.13.0
                name: kube-rbac-proxy
                ports:
                - containerPort: 8443
                  name: https
                  protocol: TCP
                resources:
                  limits:
                    cpu: 500m
                    memory: 128Mi
                  requests:
                    cpu: 5m
                    memory: 64Mi
                securityContext:
                  allowPrivilegeEscalation: false
                  capabilities:
                    drop:
                    - ALL
              - args:
                - --health-probe-bind-address=:8081
                - --metrics-bind-address=127.0.0.1:8080
                - --leader-elect
                - --leader-election-id=kcp-operator
                image: quay.io/surbania/kcp-operator:0.0.1
                livenessProbe:
                  httpGet:
                    path: /healthz
                    port: 8081
                  initialDelaySeconds: 15
                  periodSeconds: 20
                name: manager
                readinessProbe:
                  httpGet:
                    path: /readyz
                    port: 8081
                  initialDelaySeconds: 5
                  periodSeconds: 10
                resources:
                  limits:
                    cpu: 500m
                    memory: 128Mi
                  requests:
                    cpu: 10m
                    memory: 64Mi
                securityContext:
                  allowPrivilegeEscalation: false
                  capabilities:
                    drop:
                    - ALL
              securityContext:
                runAsNonRoot: true
              serviceAccountName: kcp-operator-controller-manager
              terminationGracePeriodSeconds: 10
      permissions:
      - rules:
        - apiGroups:
          - ""
          resources:
          - configmaps
          verbs:
          - get
          - list
          - watch
          - create
          - update
          - patch
          - delete
        - apiGroups:
          - coordination.k8s.io
          resources:
          - leases
          verbs:
          - get
          - list
          - watch
          - create
          - update
          - patch
          - delete
        - apiGroups:
          - ""
          resources:
          - events
          verbs:
          - create
          - patch
        serviceAccountName: kcp-operator-controller-manager
    strategy: deployment
  installModes:
  - supported: false
    type: OwnNamespace
  - supported: false
    type: SingleNamespace
  - supported: false
    type: MultiNamespace
  - supported: true
    type: AllNamespaces
  keywords:
  - kcp
  links:
  - name: Kcp Operator
    url: https://kcp-operator.domain
  maintainers:
  - email: kcp-dev@googlegroups.com
    name: kcp
  maturity: alpha
  provider:
    name: kcp.io
  version: 0.0.1
