apiVersion: v1
stringData:
  kubeconfig: |
    apiVersion: v1
    clusters:
    - cluster:
        certificate-authority: /etc/kcp/tls/server-client/ca.crt
        server: https://kcp:6443
      name: logical-cluster:admin
    contexts:
    - context:
        cluster: logical-cluster:admin
        user: logical-cluster-admin
      name: logical-cluster
    current-context: logical-cluster
    kind: Config
    preferences: {}
    users:
    - name: logical-cluster-admin
      user:
        client-certificate: /etc/kcp/logical-cluster-admin/client-cert-for-kubeconfig/tls.crt
        client-key: /etc/kcp/logical-cluster-admin/client-cert-for-kubeconfig/tls.key
kind: Secret
metadata:
  name: logical-cluster-admin-kubeconfig
type: Opaque
