# permissions for end users to edit kcps.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: kcp-editor-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: kcp-operator
    app.kubernetes.io/part-of: kcp-operator
    app.kubernetes.io/managed-by: kustomize
  name: kcp-editor-role
rules:
- apiGroups:
  - charts.kcp.io
  resources:
  - kcps
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - charts.kcp.io
  resources:
  - kcps/status
  verbs:
  - get
