apiVersion: operators.coreos.com/v1alpha1
kind: ClusterServiceVersion
metadata:
  annotations:
    alm-examples: '[]'
    capabilities: Basic Install
  name: kcp-operator.v0.0.0
  namespace: placeholder
spec:
  apiservicedefinitions: {}
  customresourcedefinitions: {}
  description: Kubernetes-like control plane
  displayName: kcp
  icon:
  - base64data: ""
    mediatype: ""
  install:
    spec:
      deployments: null
    strategy: ""
  installModes:
  - supported: false
    type: OwnNamespace
  - supported: false
    type: SingleNamespace
  - supported: false
    type: MultiNamespace
  - supported: true
    type: AllNamespaces
  keywords:
  - kcp
  links:
  - name: Kcp Operator
    url: https://kcp-operator.domain
  maintainers:
  - email: kcp-dev@googlegroups.com
    name: kcp
  maturity: alpha
  provider:
    name: kcp.io
  version: 0.0.0
